FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY *.go ./
RUN go build -o /simple-content-server

ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_NAME=$POSTGRES_NAME
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_TZ=$POSTGRES_TZ
ENV LISTEN_ON=$LISTEN_ON

EXPOSE 8080

CMD [ "/simple-content-server" ]