FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY *.go ./
RUN go build -o /simple-tasks-server

ENV POSTGRES_C_HOST=$POSTGRES_C_HOST
ENV POSTGRES_C_USER=$POSTGRES_C_USER
ENV POSTGRES_C_PASSWORD=$POSTGRES_C_PASSWORD
ENV POSTGRES_C_NAME=$POSTGRES_C_NAME
ENV POSTGRES_C_PORT=$POSTGRES_C_PORT
ENV POSTGRES_C_TZ=$POSTGRES_C_TZ

ENV POSTGRES_S_HOST=$POSTGRES_S_HOST
ENV POSTGRES_S_USER=$POSTGRES_S_USER
ENV POSTGRES_S_PASSWORD=$POSTGRES_S_PASSWORD
ENV POSTGRES_S_NAME=$POSTGRES_S_NAME
ENV POSTGRES_S_PORT=$POSTGRES_S_PORT
ENV POSTGRES_S_TZ=$POSTGRES_S_TZ

EXPOSE 8081

CMD [ "/simple-tasks-server" ]