FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY *.go ./
RUN go build -o /simple-tasks-server

ENV POSTGRES_HOST=$POSTGRES_C_HOST
ENV POSTGRES_USER=$POSTGRES_C_USER
ENV POSTGRES_PASSWORD=$POSTGRES_C_PASSWORD
ENV POSTGRES_NAME=$POSTGRES_C_NAME
ENV POSTGRES_PORT=$POSTGRES_C_PORT
ENV POSTGRES_TZ=$POSTGRES_C_TZ
ENV LISTEN_ON=$LISTEN_ON

EXPOSE 8081

CMD [ "/simple-tasks-server" ]